server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # El frontend solo conoce al API Gateway
  location /api/ {
    proxy_pass http://gateway:3000;
  }

  location /estado {
    proxy_pass http://gateway:3000;
  }

  location / {
    try_files $uri /index.html;
  }
}
